#!/bin/bash

. "$INFINITELABS_UNIFIED_DIR"/Internal/CommonFunctions.bash
. "$INFINITELABS_UNIFIED_DIR"/iPhone/BuildOptions.bash

# Assumes one .xcodeproj file only (subprojects in subdirectories!).
# Also assumes that the build settings are such that the Device SDK is set
# as the default.

for STYLE in "${STYLES[@]}"; do
	case "$STYLE" in
		Debug)
			
			# Device, Debug

			DEBUG_BUILD_SETTINGS=( "${BUILD_SETTINGS[@]}" )

			if [ "$DEVELOPMENT_IDENTITY" ]; then
				DEBUG_BUILD_SETTINGS=( "${DEBUG_BUILD_SETTINGS[@]}" CODE_SIGN_IDENTITY="$DEVELOPMENT_IDENTITY" )
			fi

			if [ "$DEVELOPMENT_PROFILE" ]; then
				DEBUG_BUILD_SETTINGS=( "${DEBUG_BUILD_SETTINGS[@]}" PROVISIONING_PROFILE="$DEVELOPMENT_PROFILE" )
			fi
			
			ILUnifiedLog "Compiling with style: '$STYLE'"
			for SETTING in "${DEBUG_BUILD_SETTINGS[@]}"; do
				ILUnifiedLog "Setting: $SETTING"
			done

			(cd "$INFINITELABS_UNIFIED_PROJECT_DIR" && \
			xcodebuild \
				-configuration "Debug" \
				"${ACTIONS[@]}" \
				"${DEBUG_BUILD_SETTINGS[@]}") || exit 1
			
			;;
		
		"Ad Hoc")

			# Device, Ad Hoc

			AD_HOC_BUILD_SETTINGS=( "${BUILD_SETTINGS[@]}" )

			if [ "$DISTRIBUTION_IDENTITY" ]; then
				AD_HOC_BUILD_SETTINGS=( "${AD_HOC_BUILD_SETTINGS[@]}" CODE_SIGN_IDENTITY="$DISTRIBUTION_IDENTITY" )
			fi

			if [ "$AD_HOC_PROFILE" ]; then
				AD_HOC_BUILD_SETTINGS=( "${AD_HOC_BUILD_SETTINGS[@]}" PROVISIONING_PROFILE="$AD_HOC_PROFILE" )
			fi

			ILUnifiedLog "Compiling with style: '$STYLE'"
			for SETTING in "${AD_HOC_BUILD_SETTINGS[@]}"; do
				ILUnifiedLog "Setting: $SETTING"
			done

			(cd "$INFINITELABS_UNIFIED_PROJECT_DIR" && \
			xcodebuild \
				-configuration "Ad Hoc" \
				"${ACTIONS[@]}" \
				"${AD_HOC_BUILD_SETTINGS[@]}") || exit 1
			

			;;
			
		"App Store")
			
			# Device, App Store

			APP_STORE_BUILD_SETTINGS=( "${BUILD_SETTINGS[@]}" )

			if [ "$DISTRIBUTION_IDENTITY" ]; then
				APP_STORE_BUILD_SETTINGS=( "${APP_STORE_BUILD_SETTINGS[@]}" CODE_SIGN_IDENTITY="$DISTRIBUTION_IDENTITY" )
			fi

			if [ "$APP_STORE_PROFILE" ]; then
				APP_STORE_BUILD_SETTINGS=( "${APP_STORE_BUILD_SETTINGS[@]}" PROVISIONING_PROFILE="$APP_STORE_PROFILE" )
			fi

			ILUnifiedLog "Compiling with style: '$STYLE'"
			for SETTING in "${APP_STORE_BUILD_SETTINGS[@]}"; do
				ILUnifiedLog "Setting: $SETTING"
			done

			(cd "$INFINITELABS_UNIFIED_PROJECT_DIR" && \
			xcodebuild \
				-configuration "App Store" \
				"${ACTIONS[@]}" \
				"${APP_STORE_BUILD_SETTINGS[@]}") || exit 1
				
			;;
			
		*)
			echo "error: Unknown build style $STYLE" >&2
			exit 1
			;;
	esac
done


