#!/bin/bash

. "$INFINITELABS_UNIFIED_DIR"/Internal/CommonFunctions.bash
. "$INFINITELABS_UNIFIED_DIR"/iPhone/BuildOptions.bash

# Assumes one .xcodeproj file only (subprojects in subdirectories!).
# Also assumes that the build settings are such that the Device SDK is set
# as the default.

(cd "$INFINITELABS_UNIFIED_PROJECT_DIR" && \
xcodebuild \
	-configuration "Debug" \
	clean && \
xcodebuild \
	-configuration "Ad Hoc" \
	clean &&
xcodebuild \
	-configuration "App Store" \
	clean) || exit 1
