#!/bin/bash

. "$INFINITELABS_UNIFIED_DIR"/Internal/CommonFunctions.bash
. "$INFINITELABS_UNIFIED_DIR"/Xcode/BuildOptions.bash

# Assumes one .xcodeproj file only (subprojects in subdirectories!).

. "$INFINITELABS_UNIFIED_DIR"/Xcode/Tasks/Clean.bash

