#!/bin/bash

function ILUnifiedLog
{
	if [ "$INFINITELABS_UNIFIED_DEBUG" == "YES" ]; then
		echo debug: "$@"
	fi
}

function ILUnifiedRunByStyle
{
	ILUnifiedLog "$INFINITELABS_UNIFIED_DIR"
	
	ACTION_NAME="$1"
	ACTION_FILE="$INFINITELABS_UNIFIED_DIR"/"$INFINITELABS_UNIFIED_PROJECT_STYLE"/"$1"
	shift
	
	export INFINITELABS_UNIFIED_PROJECT_DIR
	export INFINITELABS_UNIFIED_PROJECT_STYLE
	export INFINITELABS_UNIFIED_DIR
	export INFINITELABS_UNIFIED_DEBUG
	"$ACTION_FILE" "$@"
}